server:
  port: 3010
  
spring:
  application:
    name: nexumcms
  datasource:
    url: jdbc:postgresql://${NEXUMCMS_DB_HOST:localhost}:${NEXUMCMS_DB_PORT:5432}/${NEXUMCMS_DB_NAME:nexumcms}?createDatabaseIfNotExist=true
    driver-class-name: org.postgresql.Driver
    username: ${NEXUMCMS_DB_USERNAME:nexumcms}
    password: ${NEXUMCMS_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
